@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
 "name": "Test",
  "email": "test@gmail.com",
  "password": "12345678"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "12345678"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta 2",
  "content": "conteudo da pergunta 2"
}


###

# @name fecth_recent_questions
GET {{baseUrl}}/questions?page=1&limit=1
Content-Type: application/json
Authorization: Bearer {{authToken}}
